# Task 1.: Eigenvalues -- Basics

## Task description

- Create a function called `count_eigvals`. The function should have only one argument, which represents a symmetric real matrix as a 2D NumPy `array`. 
- The return parameter of the function should be a `list` type variable, which has pair of numbers as its elements. (Every element of the list should be a list of two values.) The first element of every pair of numbers should be an eigenvalue of the input matrix while the second one should be the multiplicity of this eigenvalue (which is the number of times an element appearing the the multiset of eigenvalues). If the input `array` is the following: 

>```python
>A=array([[1,0,0,0],
>          [0,0,1,0],
>          [0,1,0,0],
>          [0,0,0,2]])
>```

the the function should return the following `list`:

>```python
>count_eigvals(A)
>> [[-1.0,1],[1.0,2],[2.0,1]]
>
>```

- The routine should use Numpy's [`eigvalsh`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.eigvalsh.html) function, which could be used to find all eigenvalues of a symmetric or Hermitian matrix. (The `sh` at the end of the name of the `eigvalsh` function refers to these two cases.)
- **Attention:** real numbers are considered to be numerically identical, when their distance (absolute value of their difference) are smaller, than a chosen, small $\varepsilon$ number! Here let us take this value as $\varepsilon = 10^{-10}$! (Note: I've set the default value of this threshold to the machine epsilon of Python's float type values.)

- Determine the [adjacency matrix](https://en.wikipedia.org/wiki/Adjacency_matrix) of the graph below :

![](../../_img/Paley13.svg)

- There are a lot of useful tools which could help you in building the adjacency matrix, like NumPy's built-in routines for `array` [creation](https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html) or [manipulation](https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html).
- Using the `count_eigvals` function, prove by numerical calculation that the adjacency matrix has 3 different eigenvalues!
- Discuss the output of the `count_eigvals` function! Describe in your own words how many times the eigenvalues of the adjacency matrix of the examined graph are degenerate!

## Theoretical background

### Eigenvalues and multiplicity

We speak about eigenvectors and eigenvalues in the context of linear transformations. An eigenvector $\boldsymbol{\mathrm{v}}$ of a linear transformation $T$ is a vector, which changes only by a scalar factor, when that linear transformation applied to it. The factor by which the eigenvector is scaled is called as the eigenvalue $\lambda$ of an eigenvector. Formally $\boldsymbol{\mathrm{v}}$ is an eigenvector of the linear transformation $T$, if $T \left( \boldsymbol{\mathrm{v}} \right)$ is a scalar multiple of $\boldsymbol{\mathrm{v}}$:

$$
T \left( \boldsymbol{\mathrm{v}} \right)
=
\lambda \boldsymbol{\mathrm{v}}.
$$

In simpler terms we can rephrase the statements above to define eigenvectors and eigenvalues of simple matrices. In this case the same equation could be written as

$$
\underline{\underline{\boldsymbol{\mathrm{A}}}} \boldsymbol{\mathrm{v}}
=
\lambda \boldsymbol{\mathrm{v}}
$$

or in similar terms as

$$
\left(A - \lambda I \right) \boldsymbol{\mathrm{v}}
=
0
$$

where $\underline{\underline{\boldsymbol{\mathrm{A}}}}$ is a non-singular matrix. In practice a latter form is used to calculate the eigenvectors and eigenvalues by solving this system of equations.

### Adjacency matrix of a Paley graph

The graph shown above is a so called Paley graph of order 13. Generally, a Paley graph $P \left( q \right)$ with $q$ a prime power, is a graph over $q$ nodes, where two nodes are adjacent, if their difference is a square in the finite field (or Galois field) $\mathbb{F}_{q} \equiv \mathrm{GF} \left( q \right)$, or as given in [1]:

$$
E = \left\{ \left\{ u, v \right\} : u - v \in \left( \mathbb{F}_{q}^{\times} \right)^{2} \right\}
$$

In this definition the trivial $0$ solution are purposely left out. The graph is undirected if and only if $q \equiv 1 \left( \operatorname{mod} 4 \right)$ (which are prime powers of the form $4n + 1$, so $q = 5, 9, 13, \dots$ as given in the OEIS [A085759](https://oeis.org/A085759)) [2]. I only discuss these undirected cases in this task.

The set of edges could be given eg, in a form of an adjacency matrix, which is actually our task to give this matrix in this assignment. Fortunaltely if $q \equiv 1 \left( \operatorname{mod} 4 \right)$ then the $P \left( q \right)$ Paley graph has an adjacency matrix given in [4], as

$$
A
=
\frac{1}{2} \left( Q - I + J \right)
$$

where $J$ is the matrix of order $q$ with all entries equal to $1$, $I$ is the identity matrix of order $q$, and matrix $Q$ is the Jacobsthal matrix of the Galois field $\mathrm{GF} \left( q \right)$, which is symmetric with

$$
QJ
=
JQ
=
0
\quad\quad
\text{and}
\quad\quad
QQ^{T}
=
qI - J.
$$

Let us index the rows and columns of a $Q$ Jacobsthal matrix for the Galois field $\mathrm{GF} \left( q \right)$ with the $\left( u, v \right)$ ordered pairs. Using this notation every entry in the $Q$ matrix could be given as $\chi \left( u - v \right)$, where $\chi$ is the quadratic residue character of the field $\mathrm{GF} \left( q \right)$ defined by

$$
\chi \left( x \right)
=
\begin{cases}
0  & \text{if } x = 0 \\
1  & \text{if } x \in S \\
-1 & \text{otherwise},
\end{cases}
$$

where $S$ is the set of non-zero quadratic residues in the field $\mathrm{GF} \left( q \right)$.

### Sources
[1] : https://en.wikipedia.org/wiki/Paley_graph  
[2] : https://mathworld.wolfram.com/PaleyGraph.html  
[3] : https://en.wikipedia.org/wiki/Paley_construction  
[4] : Jones, Gareth A. "Paley and the Paley graphs." International workshop on Isomorphisms, Symmetry and Computations in Algebraic Graph Theory. Springer, Cham, 2016. URL: https://arxiv.org/abs/1702.00285

## Solving the task

In [1]:
import numpy as np

### Eigenvalues and multiplicity

In [2]:
def count_eigvals(A, eps=np.finfo(float).eps):
    
    assert np.linalg.det(A) != 0, "Input matrix is singular!"
    
    # Calculate eigenvalues with numpy
    # eig_A is a multiset of eigenvalues in ascending order
    eig_A = np.linalg.eigvalsh(A, UPLO='L')
    
    # Create a list for eigenvalues and their multiplicity
    eig_vals = []
    
    # Loop through all entries of the multiset of eigenvalues
    #   eig_i : element of the multiset, which means this
    #           value could occur in multiple cycles of the `for` loop
    for eig_i in eig_A:

        # Indicator whether if the current `eig_i` is aleady added to
        # the `eig_vals` list, or not
        found = False
        
        # Loop through all elements in the (eigenvalues, multiplicity) and check
        # whether if the current `eig_i` eigenvalue does already occur in it?
        for idx, eig in enumerate(eig_vals):
            # If the current `eig_i` and an already included value coincides in
            # the `eig_vals` list, then increase its multiplicity
            if abs(eig[0] - eig_i) < eps:
                eig_vals[idx][1] +=1
                found = True
                break

        # If the current `eig_i` value does not yet added to the `eig_vals` list,
        # then add it now with its multiplicity set to `1`.
        if not found:
            eig_vals.append([eig_i, 1])
    
    return eig_vals

In [3]:
A = np.array([
    [1, 0, 0, 0],
    [0, 0, 1, 0],
    [0, 1, 0, 0],
    [0, 0, 0, 2]
])

In [4]:
eig_A = count_eigvals(A)

In [5]:
print('List of eigenvalues and their multiplicity:')
for idx, eig in enumerate(eig_A):
    print('eig_{0} = {1}\tMultiplicity : {2}'.format(idx+1, eig[0], eig[1]))

List of eigenvalues and their multiplicity:
eig_1 = -1.0	Multiplicity : 1
eig_2 = 1.0	Multiplicity : 2
eig_3 = 2.0	Multiplicity : 1


### Adjacency matrix of a Paley graph

In [6]:
def quad_res_char(S, u, v):
    """
    Quadratic residue character of the Galois field GF(q).
    """
    
    d = u - v
    
    if d == 0:
        return 0
    elif abs(d) in S:
        return 1
    else:
        return -1

In [7]:
def Jacobsthal(q):
    
    # Set of (non-zero) quadratic residues in the Galois field GF(q)
    S = {i*i%q for i in range(1, q)}
    
    Q = np.zeros((q, q))
    for u in range(q):
        for v in range(q):
            Q[u][v] = quad_res_char(S, u, v)
    
    return Q

In [8]:
def paley_adjacency(q=13):
    
    assert q%4 == 1, "Order should be 1 (mod 4)!"
    
    I = np.identity(q)   # Identity matrix of order `q`
    J = np.ones_like(I)  # All-1 matrix of order `q`
    Q = Jacobsthal(q)    # Jacobsthal's matrix of the Galois field GF(q)
    
    return 1/2 * (Q - I + J)

In [9]:
q = 13
I = np.identity(q)   # Identity matrix of order `q`
J = np.ones_like(I)  # All-1 matrix of order `q`
Q = Jacobsthal(q)    # Jacobsthal's matrix of the Galois field GF(q)

In [10]:
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [11]:
J

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
Q

array([[ 0.,  1., -1.,  1.,  1., -1., -1., -1., -1.,  1.,  1., -1.,  1.],
       [ 1.,  0.,  1., -1.,  1.,  1., -1., -1., -1., -1.,  1.,  1., -1.],
       [-1.,  1.,  0.,  1., -1.,  1.,  1., -1., -1., -1., -1.,  1.,  1.],
       [ 1., -1.,  1.,  0.,  1., -1.,  1.,  1., -1., -1., -1., -1.,  1.],
       [ 1.,  1., -1.,  1.,  0.,  1., -1.,  1.,  1., -1., -1., -1., -1.],
       [-1.,  1.,  1., -1.,  1.,  0.,  1., -1.,  1.,  1., -1., -1., -1.],
       [-1., -1.,  1.,  1., -1.,  1.,  0.,  1., -1.,  1.,  1., -1., -1.],
       [-1., -1., -1.,  1.,  1., -1.,  1.,  0.,  1., -1.,  1.,  1., -1.],
       [-1., -1., -1., -1.,  1.,  1., -1.,  1.,  0.,  1., -1.,  1.,  1.],
       [ 1., -1., -1., -1., -1.,  1.,  1., -1.,  1.,  0.,  1., -1.,  1.],
       [ 1.,  1., -1., -1., -1., -1.,  1.,  1., -1.,  1.,  0.,  1., -1.],
       [-1.,  1.,  1., -1., -1., -1., -1.,  1.,  1., -1.,  1.,  0.,  1.],
       [ 1., -1.,  1.,  1., -1., -1., -1., -1.,  1.,  1., -1.,  1.,  0.]])

In [13]:
# Should be 0
print('Q * J = 0\nTest:\n', Q@J)
print()
print('J * Q = 0\nTest:\n', J@Q)
print()
print('Q * Q^T - (q * I - J) = 0\nTest:\n',(Q@Q.T) - (q*I - J))

Q * J = 0
Test:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

J * Q = 0
Test:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [14]:
A = paley_adjacency(q)

In [20]:
print('The adjacency matrix of a Paley graph of order {0}:\n{1}'.format(q, A))

The adjacency matrix of a Paley graph of order 13:
[[0. 1. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 1.]
 [1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0.]
 [0. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1.]
 [1. 1. 0. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 0. 1. 0. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 1. 0. 0.]
 [0. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 1.]
 [1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1.]
 [1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 0.]
 [0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1.]
 [1. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0.]]


The eigenvalues of a Paley graph could be analitically given for the general case. The $\lambda_{e}$ eigenvalues of a Paley graph of order $q$ are also given in [4] (seen above) as

$$
\lambda_{e}
=
\begin{cases}
\frac{1}{2} \left( q - 1 \right)            & \text{with multiplicity } 1 \\
\frac{1}{2} \left( - 1 \pm \sqrt{q} \right) & \text{with multiplicity } \frac{1}{2} \left( q - 1 \right).
\end{cases}
$$

In [16]:
print('List of THEORETICAL eigenvalues and their multiplicity:')
print('eig_1 =', 1/2 * (q - 1), '\t\t\tMultiplicity', 1)
print('eig_2 =', 1/2 * (-1 + np.sqrt(q)), '\tMultiplicity', 1/2 * (q - 1))
print('eig_3 =', 1/2 * (-1 - np.sqrt(q)), '\tMultiplicity', 1/2 * (q - 1))

List of THEORETICAL eigenvalues and their multiplicity:
eig_1 = 6.0 			Multiplicity 1
eig_2 = 1.3027756377319946 	Multiplicity 6.0
eig_3 = -2.302775637731995 	Multiplicity 6.0


In [17]:
eig_A = count_eigvals(A, eps=1e-10)

In [18]:
print('List of MEASURED eigenvalues and their multiplicity:')
for idx, eig in enumerate(eig_A):
    print('eig_{0} = {1}\tMultiplicity : {2}'.format(idx+1, eig[0], eig[1]))

List of MEASURED eigenvalues and their multiplicity:
eig_1 = -2.3027756377319952	Multiplicity : 6
eig_2 = 1.3027756377319932	Multiplicity : 6
eig_3 = 5.999999999999995	Multiplicity : 1


Which coincides our theoretical expectations.